### ISSUE TITLE
Fatal error, topic view

### ISSUE THREAD

**Issue by steffmeister** [mittwald/typo3_forum#100]
When creating posts/topics via backend following error ocurrs when trying to view the post in frontend:

`PHP Catchable Fatal Error: Argument 1 passed to Mittwald\Typo3Forum\Domain\Model\Forum\Post::checkEditOrDeletePostAccess() must be an instance of Mittwald\Typo3Forum\Domain\Model\User\FrontendUser, null given, called in [...]/typo3conf/ext/typo3_forum/Classes/Domain/Model/Forum/Post.php on line 259 and defined in [...]/typo3conf/ext/typo3_forum/Classes/Domain/Model/Forum/Post.php line 278`

Typo3 6.2.

**Comment by kpurrmann** [comment]
@steffmeister You have to declare users and groups type in backend.
