### ISSUE TITLE
'xyz.tx_typo3forum_domain_model_user_frontenduser' doesn't exist

### ISSUE THREAD

**Issue by erdling09** [mittwald/typo3_forum#102]
fresh install from repository gives the following error message on a page which includes the forum:
#1247602160: Table 'xyz.tx_typo3forum_domain_model_user_frontenduser' doesn't exist.

Users and group are existing and are having the correct type: typo3_forum user and typo3_forum group.
I also checked setup ts for correct mapping. 
Something has to be missing, doing a database table copy of fe_users to tx_typo3forum_domain_model_user_frontenduser will solve that issue.

**Comment by DavidSporer** [comment]
Same problem here on a fresh installation of TYPO3 7.6.2

**Comment by Idleworks** [comment]
This problem occurs only sometimes in my syslog. The requested URL is eID=typo3_forum&tx_typo3forum_ajax%5Bformat%5D=json&tx_typo3forum_ajax%5Baction%5D=main&tx_typo3forum_ajax%5Bcontroller%5D=Ajax&cHash=XXX

TYPO3 then doesn't respect table mappings set in typoscript. weird...
