### ISSUE TITLE
Upgrade Script mmForum Database tables from 1.9x to 2.0 

### ISSUE THREAD

**Issue by velletti** [mittwald/typo3_forum#11]
i would do this issue, but  if there is any existing Script (also not final ), it will help ..

**Comment by mirkokaufmann** [comment]
Hello @velletti

did you work on this script already? 

Greetings 
Mirko

**Comment by stefan72** [comment]
Also interested in this issue. It would help typo3-forum to get a good start :)

**Comment by selim-hausformat** [comment]
Guten Tag

Vielen Dank für Ihre Nachricht. Ich bin vom 18.07.2015 bis 09.08.2015 abwesend. Diese Nachricht wird nicht weitergeleitet.

Bei dringenden Fällen schreiben Sie eine E-Mail an: support@hausformat.com

Freundliche Grüsse
Selim Imoberdorf

—
.hausformat
Rohrerstrasse 20
5000 Aarau
+41 (0)62 823 86 80
www.hausformat.com

Folgen Sie uns:
www.facebook.com/hausformat
plus.google.com/+hausformat

Benötigen Sie Unterstützung?
Wir helfen Ihnen gerne
über unsere Supportadresse:
support@hausformat.com

**Comment by velletti** [comment]
I sent Mirko the updated Scripts to give it a try. Actually this is just a standalone Script without any TYPO3 integration (not a backend Tool ! ) as it needs two databases for a smooth update from an old 4.5 plattform to a new 6.2 Version. 

and the tool needs to be run from command line.

For me it finally worked, also i still have some unsolved Issues during Upgrade, as we used a modified version of mmForum 1.9. :


f.e. we had  already a field sys_language_uid to differ between languages, we used tt-rating to vote for good answers, Toics ( i still need to write a converter to cpnvert this ratings to new Voting in new typo3-forum) and we had an additional  field "Software Version" that i need to convert ot a tag.

**Comment by stefan72** [comment]
Can someone give an update to this issue? There are many mm_forum installations out there and I believe many integrators would be happy if they could move to the new forum.

**Comment by pstranghoener** [comment]
Hey everyone, 

we are working on an migration script already and we give an update when its done..

**Comment by nibelungen** [comment]
Any update on this?? 

best regards

**Comment by pstranghoener** [comment]
The Feature is in version 1.1.0 included
