### ISSUE TITLE
Bootstrap 3 compatibility ???

### ISSUE THREAD

**Issue by Lobster1956** [mittwald/typo3_forum#141]
Are there plans to modify the Templates/Partials for Bootstrap 3 ???

**Comment by pstranghoener** [comment]
Hey, there are no plans yet. I tagged it as an enhancement

**Comment by mavoIn** [comment]
hi, i added bootstrap 3 resources and templates to my lokal extension. And i added special static templates to make bootstrap 2 or 3 additional. 

Will someone test my changes local? at the moment i'm not able to push it via pull request :-(

**Comment by pstranghoener** [comment]
@mavoIn Why are you not able to push it via a pull request? You can send your changes to opensource@mittwald.de ? and we will test it and make a PR. ;)
