### ISSUE TITLE
better using standard tx_extbase_type

### ISSUE THREAD

**Issue by Lobster1956** [mittwald/typo3_forum#142]
hi...
for working with other extensions together they NEED the original type **Tx_Extbase_Domain_Model_FrontendUser** it would be neccesary that typo3_forum does this also !!!
In my case this was jobfair and typo3_forum... I know that this is a little breaking chance _(modifying the tx_extbase_type in the existing datatables)_, but, better now than later !!!
As i have testet, It is only this TS for FE:

config.tx_extbase.persistence.classes {  
  TYPO3\CMS\Extbase\Domain\Model\FrontendUser.subclasses {
    Mittwald\Typo3Forum\Domain\Model\User\FrontendUser = Mittwald\Typo3Forum\Domain\Model\User\FrontendUser
  }
  Mittwald\Typo3Forum\Domain\Model\User\FrontendUser {
    mapping.tableName = fe_users
    mapping.recordType = Tx_Extbase_Domain_Model_FrontendUser
  }
  TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup.subclasses {
    Mittwald\Typo3Forum\Domain\Model\User\FrontendUserGroup = Mittwald\Typo3Forum\Domain\Model\User\FrontendUserGroup
  }
  Mittwald\Typo3Forum\Domain\Model\User\FrontendUserGroup {
    mapping.tableName = fe_groups
    mapping.recordType = Tx_Extbase_Domain_Model_FrontendUserGroup
  }
}    

and for BE changing the TCA overrides...

**Comment by macjohnny** [comment]
+1

**Comment by pstranghoener** [comment]
@Lobster1956 Please make a pull request for that and we will merke it. Thanks.

**Comment by vendytjung** [comment]
i try with this:
`Mittwald\Typo3Forum\Domain\Model\User\FrontendUser {
	mapping.recordType >
}
Mittwald\Typo3Forum\Domain\Model\User\FrontendUserGroup {
	mapping.recordType >	
}`

Forum still work in Frontend. see any problem?

**Comment by macjohnny** [comment]
@vendytjung can you explain what you did and what doesn't work?

**Comment by vendytjung** [comment]
@macjohnny: i have only add the typoscript (see top)

Testing until now:

Work:
- forum overview :heavy_check_mark:
- forum post :heavy_check_mark:
- comment post :heavy_check_mark:
- create post :heavy_check_mark:
- edit post :heavy_check_mark:

doesn't work:
still testing

**Comment by pstranghoener** [comment]
Could this Issue be closed?

**Comment by macjohnny** [comment]
@pstranghoener as soon as https://github.com/mittwald/typo3_forum/pull/197 is merged

**Comment by pstranghoener** [comment]
I think his is an breaking change and could not been merged for now.

**Comment by vendytjung** [comment]
Yes, it think there ist a breaking change, without DB update tx_extbase_type to NULL, it's a problem

**Comment by macjohnny** [comment]
@vendytjung can you provide the update script?

**Comment by vendytjung** [comment]
i can write class.ext_update.php for DB update

**Comment by pstranghoener** [comment]
Could this issue be closed?

**Comment by macjohnny** [comment]
@pstranghoener I still believe that the record type should be changed as suggested in https://github.com/mittwald/typo3_forum/pull/197, but if you don't want to have that, then you can close this issue.

**Comment by pstranghoener** [comment]
We don't want to change that for now, maybe in a later release.
