### ISSUE TITLE
Subscribe/Unsubscribe not working

### ISSUE THREAD

**Issue by nicozerr** [mittwald/typo3_forum#153]
Hi.

It's not possible for me to unsubscribe to a topic. If I click on Subscribe, my user is added to the topic, but the (ajax) menu continue to show Subscribe button.
Maybe it's a cache issue with eid.

TYPO3 7.6.10
typo3_forum 1.0.3

**Comment by bihor** [comment]
I have the same problem.

**Comment by bihor** [comment]
There is another problem: the links in the email are not absolute. The domain is missing in the link.
The links should be generated this way:
$this->uriBuilder->setTargetPageUid($this->settings['pids']['Forum'])->setCreateAbsoluteUri(TRUE)->setArguments($arguments)->build();
or this way:
$this->uriBuilder->setCreateAbsoluteUri(FALSE);
$link = $this->uriBuilder->setTargetPageUid($this->settings['pids']['Forum'])->setCreateAbsoluteUri(TRUE)->setArguments($arguments)->build();
$topicLink = \TYPO3\CMS\Core\Utility\GeneralUtility::locationHeaderUrl($link);

Nevertheless: the repaired unsubscribe link doesn´t work. 
When a user click at the unsubscribe link in the email, nothing happens. The user still remains subscribed.
He will see the post and topics with the link to subscribe.
=> it is not possible to unsubscribe anyway.

**Comment by mojobsb** [comment]
TYPO3 7.6.16
typo3_forum 1.0.4
I still have this problem and it seems to be a caching problem:
When I click the subscribe/unsubscribe link it is working the first time. When I click the link again the button doesn't change back. In the DB I can see the subscription (tx_typo3forum_domain_model_user_forumsubscription or tx_typo3forum_domain_model_user_topicsubscription)
When I use "clear system caches" in the backenend the button changes to the correct state but is only working correctly once again (as in the beginning).

Why was the issue closed? Did I miss something?

**Comment by magesticmojo** [comment]
@kpurrmann Can we reopen this issue? I still have this issue as described above.
@bihor Didn't realize you already posted the solution for absolute links in notification mails. I submitted it as merge request here #208

**Comment by Piperback** [comment]
@kpurrmann
Can you please reopen this issue? 

If you toggle between subscribe/unsubscribe the behavior is exactly like **magesticmojo** described it. 

TYPO3 7.6.14
typo3_forum 1.0.4

**Comment by pstranghoener** [comment]
I will close that issue again, because the fix its already in the develop branch and we will release a new version in the next couple of days.

**Comment by magesticmojo** [comment]
@pstranghoener Sorry to bother you again, but I still have the same issue with typo3_forum 1.1.0 and TYPO3 7.6.20
Can we please reopen this issue?

**Comment by iunctim** [comment]
This issue still exists (also in the 1.0-dev version), we've tried everything to fix it, but nothing works. When will the fixed version be released?

**Comment by julianwinkel** [comment]
I think it is a cache problem with the ifViewHelper (mmf:user.ifSubscribed) used in .../Ajax/TopicListMenu.html and ForumMenu.html 

As Workaround we use a simple ViewHelper that return a boolean value. It works for us.

IfSubscribedViewHelper.php
```php
<?php
/**
 * COPYRIGHT NOTICE
 *
 * Copyright (c) 2017 Neue Rituale GbR
 * @author Julian Winkel <code@neuerituale.com>
 * @version 1.0.0
 *
 * This file is part of the typo3_forum project.
 */

namespace NR\Typo3Forum\ViewHelpers\Forum;

/**
 * ViewHelper that renders its contents, when a certain user has subscribed
 * a specific object.
 */
class IfSubscribedViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper
{

	/**
	 * @param null $object
	 * @return string
	 */
	public function render($object = null)
	{
		foreach ($object as $subscriber) {
			if ($subscriber->getUid() == (int)$GLOBALS['TSFE']->fe_user->user['uid']) {
				return true;
			}
		}
		return false;
	}
}
```

.../Resources/Private/Templates/Bootstrap/Ajax/TopicListMenu.html
```php
{namespace nr=NR\Typo3Forum\ViewHelpers}

/* ... */

<mmf:authentication.ifLoggedIn>
	<f:if condition="{nr:forum.ifSubscribed(object: '{topic.subscribers}')}">
		<f:then>
			<f:link.action controller="User" action="subscribe" class="btn" arguments="{topic: topic, unsubscribe: 1}">
				<f:translate key="Button_Unsubscribe" />
			</f:link.action>
		</f:then>
		<f:else>
			<f:link.action controller="User" action="subscribe" class="btn" arguments="{topic: topic}">
				<f:translate key="Button_Subscribe" />
			</f:link.action>
		</f:else>
	</f:if>
</mmf:authentication.ifLoggedIn>
```

**Comment by iunctim** [comment]
That actually did the trick, we had to change one line in your template snippet to make it work:
< 	<f:if condition="{nr:**forum**.ifSubscribed(object: '{topic.subscribers}')}">
> 	<f:if condition="{mmf:**user**.ifSubscribed(object: '{forum.subscribers}')}">
Thanks a lot and have a nice weekend!

**Comment by julianwinkel** [comment]
Cool :). Yes we put the file in another subfolder like "Viewhelpers/Forum/IfSubscribedViewHelper.php".
