### ISSUE TITLE
Pagination HTML

### ISSUE THREAD

**Issue by sxbxstxxn** [mittwald/typo3_forum#182]
I'm searching for the HTML code of the Forum Pagination/ Topic Pagination. The Extension creates the following html code for it:

`<ul class="f3-widget-paginator"><li class="current">1</li></ul>`

But the files in ...Templates\ViewHelpers\Widget\Paginate are showing different code snippets (for example `<li class="disabled">` and starting with `<div class="pagination pagination-right">`) and changing it has no effect. 

So where can I find and change it?

**Comment by mgrundkoetter** [comment]
Have you tried Google? Found links like
http://blog.teamgeist-medien.de/2014/11/typo3-fluid-viewhelper-templates-ueberschreiben-z-b-vom-paginate-widget.html and https://forge.typo3.org/issues/73207 which may be relevant. The pagination widget is part of the fluid extension itself, as it is a reusable component. So the templates can also be found there (typo3/sysext/fluid/Resources/Private/Templates).

**Comment by pstranghoener** [comment]
@sxbxstxxn Could this Issue been closed?
