### ISSUE TITLE
View not found when creating a Topic

### ISSUE THREAD

**Issue by DavidSporer** [mittwald/typo3_forum#185]
I have set up typo3-forum as described in the manual and added the TypoScript templates.
I can see the view that is described in the manual when accessing my forum-page in the frontend.
When I try to create a new topic it gives me the error 
**"The technical reason is: No template was found. View could not be resolved for action "create" in class "Mittwald\Typo3Forum\Controller\TopicController"."**
This shouldn't happen because the createAction of TopicController forwards to another action. Does one of you guys know what the problem could be?

**Comment by velletti** [comment]
I think there is a misconfiguration during one of the steps before the redirect, that throws an exception: 

The easiest way to find the content of the exception
create a Template\Topic\Create.html 
```
<f:layout name="default"/>
<f:section name="main">
	this ist only shown in case of an Error!
</f:section>
<f:section name="menu"/>
```

then you will get from the layout the flash message with the exception with maybe more infos about the reason ..

**Comment by DavidSporer** [comment]
Thank you very much!
I found the error, though I'm not quite sure how to solve it yet.
The thing is that I've set up a fe-register page that creates default fe users. If I edit that user and tell the system that it should be typo3_forum_user it works but then the other stuff like editing the profile via the femanager doesn't work anymore.

**Comment by pstranghoener** [comment]
May it helps if you put that typoscript in the constants

plugin.tx_srfeuserregister_pi1.keepUnselectableUserGroups = uid of usergroup 

Best Regards Philipp

**Comment by DavidSporer** [comment]
No that didn't help.
I assume the issue is that femanager is extending the feuser model as typo3 forum does as well.

**Comment by DavidSporer** [comment]
$userRepository->findByUid isn't returning the user if I set the typo3_forum_user setting which makes sense since the UserRepository is the one that femanager is using.

**Comment by mocsap** [comment]
I have the same problem with my Typo3 6.2.30 instance. Following error appears when I'm trying to create a new post:

> The technical reason is: No template was found. View could not be resolved for action "create" in class "Mittwald\Typo3Forum\Controller\TopicController".

Have you found the solution, or the exact reason what needs to be done to get the forum plugin to work?

**Comment by mocsap** [comment]
Is there any known workaround to this issue?

**Comment by mocsap** [comment]
I have double checked the installation steps, configuration and everything looks ok. I have also installed the latest typo3_forum release 1.0.4. Unfortunately, still the same error appears.

_Sorry, the requested view was not found.
The technical reason is: No template was found. View could not be resolved for action "create" in class "Mittwald\Typo3Forum\Controller\TopicController"._

Maybe someone has any idea, please?

**Comment by pstranghoener** [comment]
It sound like the templates are not found. Did you made your own templates?

**Comment by mocsap** [comment]
Hello Philipp, thank you for your response and for this hint!

Yes, I'm using an own template, created in Templavoila. This is a standard template which is used on all my pages also with other extensions. The extension output is placed on the right side. Please note that this error happens at the time of submitting a new forum post. I can see the subforums and write a new forum topic. This error appears at the time when I'm trying to submit the topic.

<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3DataStructure>
	<meta type="array">
		<langDisable>1</langDisable>
	</meta>
	<ROOT type="array">
		<tx_templavoila type="array">
			<title>ROOT</title>
			<description>Select the HTML element on the page which you want to be the overall container element for the template.</description>
		</tx_templavoila>
		<type>array</type>
		<el type="array">
			<field_subnavimitgl type="array">
				<tx_templavoila type="array">
					<title>subnavimitgl</title>
					<sample_data type="array">
						<numIndex index="0"></numIndex>
					</sample_data>
					<eType>TypoScriptObject</eType>
					<preview></preview>
					<TypoScriptObjPath>lib.subnavimitgl</TypoScriptObjPath>
					<proc type="array">
						<int>0</int>
						<HSC>0</HSC>
						<stdWrap></stdWrap>
					</proc>
				</tx_templavoila>
			</field_subnavimitgl>
			<field_headline type="array">
				<tx_templavoila type="array">
					<title>headline</title>
					<sample_data type="array">
						<numIndex index="0"></numIndex>
					</sample_data>
					<eType>TypoScriptObject</eType>
					<preview></preview>
					<TypoScriptObjPath>lib.headline</TypoScriptObjPath>
					<proc type="array">
						<int>0</int>
						<HSC>0</HSC>
						<stdWrap></stdWrap>
					</proc>
				</tx_templavoila>
			</field_headline>
			<field_rechteseite type="array">
				<tx_templavoila type="array">
					<title>Rechte Seite</title>
					<sample_data type="array">
						<numIndex index="0"></numIndex>
					</sample_data>
					<eType>ce</eType>
					<TypoScript>
10= RECORDS
10.source.current=1
10.tables = tt_content</TypoScript>
					<preview></preview>
					<enableDragDrop type="integer">1</enableDragDrop>
				</tx_templavoila>
				<TCEforms type="array">
					<label>Rechte Seite</label>
					<config type="array">
						<type>group</type>
						<internal_type>db</internal_type>
						<allowed>tt_content</allowed>
						<size>5</size>
						<maxitems>200</maxitems>
						<minitems>0</minitems>
						<multiple>1</multiple>
						<show_thumbs>1</show_thumbs>
					</config>
				</TCEforms>
			</field_rechteseite>
		</el>
	</ROOT>
</T3DataStructure>
```

**Comment by pstranghoener** [comment]
Is this issue still alive or you need help?

**Comment by sksksksk** [comment]
I just hit this issue. But my problem was that my user didn't have the typo3_forum_user option set in the user editing screen. And as far as I understand, this was the same problem this issue originally was created.

**Comment by vdespa** [comment]
Thanks @sksksksk 

![screen shot 2017-12-15 at 15 40 41](https://user-images.githubusercontent.com/1197635/34046778-71cd21c6-e1ae-11e7-8521-bea8d7447c29.png)
