### ISSUE TITLE
Attachments are not processed when creating a new post.

### ISSUE THREAD

**Issue by MrP1ff** [mittwald/typo3_forum#194]
Hi,

the enctype attribute is missing in the standard template for the new post form:  https://github.com/mittwald/typo3-forum/blob/develop/Resources/Private/Partials/Standard/Post/Form.html

This prevents attachments from being processed properly when creating a new post. This is not an issue in the bootstrap version or in the template for the new topic form.

It is easily fixed by adding `enctype="multipart/form-data"` to the form element.

Cheers,

Markus

**Comment by linuxdog** [comment]
Hello,
I can't upload any attachments, even by using the bootstrap-post-form with right enctype.
No error, but also no attachment. Nothing new in tx_typo3forum_domain_model_forum_attachment.

Same with new Thread: Everything works, but no attachment.
Attachments that I imported (from the old mm_forum) are shown in the old posts and can be downloaded.

I'm using 1.0.4, where I have to set the ACL for newAttachment manually.

Are the attachments working anywhere?

Greetings, Stefan
