### ISSUE TITLE
typo3_forum & TYPO3V8

### ISSUE THREAD

**Issue by typo3-solution** [mittwald/typo3_forum#199]
Hi there,
i want to install the typo3_forum on a TYPO3V8.5 - Version.
First we have to remove the part 'renderMode="div"' from the file:  typo3_forum/Resources/Private/Layouts/Standard/Default.html.
The Output works, but the "create new topic" - link, doesn't work. I get the following error:
`    Call to a member function evaluateChildNodes() on null
     
    Error thrown in file
    C:\xampp\htdocs\TYPO3\vendor\typo3fluid\fluid\src\Core\ViewHelper\AbstractViewHelper.php in line 284.
     
    TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper::renderChildren()
     
    C:\xampp\htdocs\TYPO3\typo3\sysext\fluid\Classes\ViewHelpers\CObjectViewHelper.php:
    00133:         }
    00134:         if ($data === null) {
    00135:             $data = $this->renderChildren();
    00136:         }
    00137:         $currentValue = null;
     
     
    TYPO3\CMS\Fluid\ViewHelpers\CObjectViewHelper::render("plugin.tx_typo3forum.renderer.icons.forum_new", array)
     
    C:\xampp\htdocs\TYPO3\typo3conf\ext\typo3_forum\Classes\ViewHelpers\Forum\ForumIconViewHelper.php:
    00067: 
    00068:         if ($data['new']) {
    00069:             return $this->getCObjectViewHelper()->render('plugin.tx_typo3forum.renderer.icons.forum_new', $data);
    00070:         } else {
    00071:             return $this->getCObjectViewHelper()->render('plugin.tx_typo3forum.renderer.icons.forum', $data);
     
     
    Mittwald\Typo3Forum\ViewHelpers\Forum\ForumIconViewHelper::render(Mittwald\Typo3Forum\Domain\Model\Forum\Forum, 32, "")`

In Line 284:
` return $this->viewHelperNode->evaluateChildNodes($this->renderingContext);`

I figured out, that '$this->renderingContext' is empty. Any ideas!? :)

Liebe Grüße - Simon

**Comment by pstranghoener** [comment]
The Extension is not v8 compatible at the moment, we will start developing it for v8 until April...

**Comment by kaufi02** [comment]
Is there already an expected release-date for the v8 version?

**Comment by pstranghoener** [comment]
@kaufi02 Not at the moment, we are working on it. But it will take a while its not very easy job to do that.

**Comment by mocsap** [comment]
@pstranghoener It will be really great to have it in v8. Thanks for working on this.

**Comment by typo3-solution** [comment]
yea, @pstranghoener!!! :-* Can't wait! ^^
If you need help, i will help you...

"So gut ich eben kann!" ;)

**Comment by typo3-solution** [comment]
@pstranghoener 
Hey Philipp, 
thanks for your work, your time, and your skills! 
Do you have any news for us?! :) What do you think about the release of the "typo3_forum" for TYPO3V8?

**Comment by pstranghoener** [comment]
@typo3-solution

Hey Simon, 
sorry to say but not new information on that topic. Currently we are working on a solutions to perform updates continuously and than this is the first topic. 

Best Regards Philipp

**Comment by typo3-solution** [comment]
Hey Philipp,
i will report all my Changes, für the TYPO3V8. I hope, it will help you! (or someone else?)
**Resources\Private\Layouts\Standard:**
`_<f:flashMessages renderMode="div"/>_
<f:flashMessages as="div"/>`

**Resources\Private\Layouts\Bootstrap:**
`_<f:flashMessages renderMode="div"/>_
<f:flashMessages as="div"/>`

Replace TYPO3\CMS\Fluid\ViewHelpers with TYPO3Fluid\Fluid\ViewHelpers. For example on:
- \typo3_forum\Classes\ViewHelpers\IfInstanceOfViewHelper.php
Details on: https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.0/Breaking-69863-ChangesInViewHelpersPostFluidStandalone.html

If a Viewhelper returns HTML, add following lines at the Class:
`protected $escapeOutput = false;
protected $escapingInterceptorEnabled = false;`

I have to add the following SQL:
ALTER TABLE `fe_groups` ADD `tx_typo3forum_user_mod` BOOLEAN NOT NULL AFTER `TSconfig`;

Currently, it starts running with TYPO3v8! ;-)

**Comment by typo3-solution** [comment]
Still having following Problem: 
Found this function in the Viewhelper:
`/**
 * @return CObjectViewHelper
 */
protected function getCObjectViewHelper()
{
        return $this->objectManager->get('TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper');
}`

Returns this Error:
Call to a member function evaluateChildNodes() on null
Error thrown in file
**/**/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 284.

Setting the following Line inactive:
`return $this->getCObjectViewHelper()->render(...);`
is not the solution! :-) Any ideas?

**Comment by verdure-peuser** [comment]
We already started the upgrade on our own. a pull request with wip is here #232

**Comment by Gregor-Agnes** [comment]
Is there any progress on this? We have to update a very huge site with some forum and calendars and news and and and :) running under 6.2 ELTS
Since it is a big effort, we would like to update to 8.7. typo3_forum is the only extension, which prevents us from doing so. 
It would be very helpful to know, if the update is coming or not and, if possible, the approximate date. 
Is that possible?

Btw: thx for your great work!

**Comment by kpurrmann** [comment]
Hopefully we will release a stable release for TYPO3 8LTS this January.
First of all we want to get through older bugs and then start working on V8.

**Comment by kpurrmann** [comment]
#232

**Comment by BastianBalthasarBux** [comment]
Any news on that? ATM the extension still remains as marked compatible for 6.2x to 7.x, here on git as well as on TER.

**Comment by pstranghoener** [comment]
No any news on that, we are not allowed to upload a new version.

**Comment by BastianBalthasarBux** [comment]
:-(

**Comment by Gregor-Agnes** [comment]
Hm, what does that mean? 
Why are you not allowed to upload a new version? And by whom? 
Is typo3_forum dead?

**Comment by pstranghoener** [comment]
Its not dead any we have a version for 8 but we are no allowed to pulish it by now. 
W ecan not say anything more to that. Sorry!

**Comment by w0nk1** [comment]
Srsly!? Any further information? Why would you hold back a functional extension? I don't get it?

**Comment by pstranghoener** [comment]
I repeat my last sentence with a short addition:
We are not allowed to say anything more to that!

**Comment by typo3-solution** [comment]
TYPO3 - inspiring people to share...

**Comment by pstranghoener** [comment]
We know that, but that are not our Guidlines!
