### ISSUE TITLE
Topic subscription - Domain name missing in link

### ISSUE THREAD

**Issue by mocsap** [mittwald/typo3_forum#203]
Hi,

I have a problem with a missing domain name in the automatically generated link received in mail from a forum. The current mail structure looks like:

Hallo stat04,

stat02 hat einen Beitrag in dem von dir abonnierten Thema Test stat04 erstellt.
Falls Du keine Benachrichtigungen mehr erhalten möchtest, klicke im Forum auf den Button /mitgliederbereich/mitgliederforum/?tx_typo3forum_pi1%5Btopic%5D=5&tx_typo3forum_pi1%5Bcontroller%5D=User&tx_typo3forum_pi1%5Baction%5D=subscribe&tx_typo3forum_pi1%5Bunsubscribe%5D=1&cHash=9....

How can I add the missing domain to the beginning od this link?

Another question. Is it possible to display a full user name instead of the forum login names?

Thank you very much for your help.

**Comment by mocsap** [comment]
Any suggestion? I assume that this is a simple configuration parameter.

**Comment by magesticmojo** [comment]
#208

**Comment by pstranghoener** [comment]
Fix in Version 1.1.0 included.
