### ISSUE TITLE
I want some Text from the topic in the topic list

### ISSUE THREAD

**Issue by ak1982** [mittwald/typo3_forum#206]
Is that possible?

In the moment I get this view:

http://dev.intranet.erfolg-im-beruf.de/?id=112&tx_typo3forum_pi1[forum]=2&tx_typo3forum_pi1[action]=show&tx_typo3forum_pi1[controller]=Forum&cHash=68739aa5957692f05545601abf0156b3

And now I want the text from the first post on the list side.

Thanks for answering

**Comment by pstranghoener** [comment]
Hey @ak1982, 

if i click on the link i only see an login screen. 

Best Regards Philipp

**Comment by ak1982** [comment]
Oh yes, sorry. Here a picture
![screen shot 2017-04-12 at 12 44 05](https://cloud.githubusercontent.com/assets/2596915/24953984/bd1481fe-1f7d-11e7-923b-67d371899aef.png)

**Comment by ak1982** [comment]
It would be great if there is a chance to put the text also in the list view.
Another little question. Is it possible to unlink the Author and to use the Full name of the author?

Best regards
Andreas

**Comment by pstranghoener** [comment]
It could be posible than must do it on yout own and put in your own template...

**Comment by pstranghoener** [comment]
Can i close that issue?

**Comment by pstranghoener** [comment]
I will close that ticket because of no reaction of the author.
