### ISSUE TITLE
form for posting absent

### ISSUE THREAD

**Issue by mvnaz** [mittwald/typo3_forum#223]
I use typo3_forum with femanager. And all good but form for posting absent. Where can be a problem ?

**Comment by pstranghoener** [comment]
Did you set all the ACLs mentioned here? http://typo3-forum.readthedocs.io/en/master/Configuration/Installation/Index.html

**Comment by mvnaz** [comment]
yes thank you! I solved problem )01.08.2017, 10:57, "Philipp Stranghöner" <notifications@github.com>:Did you set all the ACLs mentioned here? http://typo3-forum.readthedocs.io/en/master/Configuration/Installation/Index.html
