### ISSUE TITLE
Fatal error when opening post on typo3_forum 1.1.0 and typo3 7.6.14

### ISSUE THREAD

**Issue by mwaldheim** [mittwald/typo3_forum#229]
Hello,
I have the typo3_forum extension installed on my homepage. We installed the plugin with this manual: http://typo3-forum.readthedocs.io/en/master/KnownProblems/Index.html

We have set up everything exactly according to the above instructions and urgently need a solution.

BUT now we have a fatal error

![image](https://user-images.githubusercontent.com/31657644/30062345-23333e5e-924b-11e7-9113-fcbca90b3ab8.png)

We have used typo3_forum 1.1.0 and typo3 7.6.14 in our company. But when I click on the post, the above error comes.

![image](https://user-images.githubusercontent.com/31657644/30062338-1f8f8082-924b-11e7-849d-1adc3851e122.png)

**Comment by pstranghoener** [comment]
Hey, 

which PHP Version are you using? 

Best Regards Philipp

**Comment by mwaldheim** [comment]
Hey,

i used PHP-Version 5.5.38

Best Markus Waldheim

**Comment by velletti** [comment]
maybe an issue with the field extbase_type in table "fe_users"  ?

until the logged in Frontend user isn´t from type 
tx_extbase_type = Mittwald\Typo3Forum\Domain\Model\User\FrontendUser

i also got this issue (in one of the first forums versions)

**Comment by mwaldheim** [comment]
Where can I set this? With us, the users are retrieved by our server via REST-API and temporarily stored in TYPO3. Could that be a problem?

Looking forward to a brief explanation.

**Comment by pstranghoener** [comment]
Hey, 

if you had read the entire manual as you said, you found that point. The user and the usergroup must have the Record Type “typo3_fourm user” and “typo3_forum group”. You must define it in the Extend Tab in the user or usergroup record.

http://typo3-forum.readthedocs.io/en/master/Configuration/RegisterandLogin/Index.html

Best Regards Philipp

**Comment by velletti** [comment]
As philip 2 seconds ago wrote .. 

If you have a look at the typoscript Setup.txt in Configuration folder, you will see that in Case of using extension sf_register, the field "tx_extbase_type " is automaticalle prefilled with this value : 
"Mittwald\Typo3Forum\Domain\Model\User\FrontendUser"

so if you get you User via REST, and store it to the DB (like we also do it) just set this value during the REST API function when storing to the db 
OR
change fe_users.sql and set the default value of 
tx_extbase_type to Mittwald\Typo3Forum\Domain\Model\User\FrontendUser

**Comment by mwaldheim** [comment]
okay, if I do it now as in the manual, my mistake is gone. Instead of the old error comes a new one:

![image](https://user-images.githubusercontent.com/31657644/30098799-c194e79e-92e3-11e7-8a07-dc439ff73273.png)


I have assigned to the user manually under Extended the Usergroup "typo3_forum group". Here is my PHP script, which creates the user. What would be the parameter for the user's array to specify this extended configuration directly when a user is created?

![image](https://user-images.githubusercontent.com/31657644/30098800-c666e66e-92e3-11e7-9a95-b04622473f28.png)


Thanks for ur support.

**Comment by pstranghoener** [comment]
As @velletti already said in the post before the tx_extbase_type must have the value Mittwald\Typo3Forum\Domain\Model\User\FrontendUser

**Comment by velletti** [comment]
addthis to the newUserInDb Array

'usergroup' => "Mittwald\\Typo3Forum\\Domain\\Model\\User\\FrontendUser" ,  

(i think you have to mask the "\" sign with another "\" )

and to your new Error: 
your Usergroup 1 must be  extbase_type  ypo3_forum group

**Comment by pstranghoener** [comment]
Could we close this? @mwaldheim

**Comment by mwaldheim** [comment]
I think we have it. But i must fix it with my development chef. But thanks for ur help.

**Comment by mwaldheim** [comment]
I have a new Problem.

After i fixed the Usergroups and tx_extbase_type, i logged in with the dummy and click on a forum theme and become a new error. Can u tell me, what is wrong?

![image](https://user-images.githubusercontent.com/31657644/30415709-90c6c1fe-9929-11e7-89b3-b810f648c88b.png)
