### ISSUE TITLE
[url=www.mittwald.de]tolles forum[/url]

### ISSUE THREAD

**Issue by typo3-solution** [mittwald/typo3_forum#235]
Hey everyone,
in the old version, you where able to set links like above. In the new version, the output is wrong/missing :-(
How must i change this line / add a new line:
$ret = preg_replace_callback('#([\s>])([\w]+?://[\w\\x80-\\xff\#$%&~/.\-;:=,?@\[\]+]*)#is', [&$this, 'makeUrlClickable'], $ret);
to get it right!?

**Comment by heikohaensge** [comment]
Oh yes, this would be nice to have, especially after migrating from mm_forum, so all the former link entries are parsed correctly again.

**Comment by heikohaensge** [comment]
@pstranghoener : No response in weeks... Anybody here for support?

**Comment by kpurrmann** [comment]
You could do it on your own if you add following text parsing component:
BBCode Wrap: [url=][/url]
Regular Expression: /\[url=(.*)\](.*)\[\/url\]/
Replacement Pattern: <a href="$1">$2</a>
