### ISSUE TITLE
tx_typo3forum_domain_model_user_frontendusergroup' doesn't exist

### ISSUE THREAD

**Issue by danielmacht** [mittwald/typo3_forum#249]
Hi,
after downloading typo3_forum 1.1.0 to a fresh installation of typo3 7.6.24 (running on XAMPP/PHP 7.2.1/Apache 2.4.29/MySQL 10.1.30 MariaDB) and following the installation instructions [here](http://typo3-forum.readthedocs.io/en/master/Configuration/Installation/Index.html) I encounter the following error : _Oops, an error occurred! Code: 2018031312495232fd9c7f_

please find the complete error log below:

`Tue, 13 Mar 2018 12:49:53 +0100 [ALERT] request="db6ebbcd68854" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 2018031312495232fd9c7f - {"exception":"TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Exception\\SqlErrorException: Table 'typo3_v7.tx_typo3forum_domain_model_user_frontendusergroup' doesn't exist in C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Storage\\Typo3DbBackend.php:896\nStack trace:\n#0 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Storage\\Typo3DbBackend.php(433): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbBackend->checkSqlErrors()\n#1 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Storage\\Typo3DbBackend.php(410): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbBackend->getRowsFromDatabase(Array)\n#2 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Storage\\Typo3DbBackend.php(360): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbBackend->getRowsByStatementParts(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#3 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Backend.php(226): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Storage\\Typo3DbBackend->getObjectDataByQuery(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#4 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\PersistenceManager.php(127): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Backend->getObjectDataByQuery(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#5 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\QueryResult.php(115): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\PersistenceManager->getObjectDataByQuery(Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Query))\n#6 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(568): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult->getFirst()\n#7 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(514): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->mapResultToPropertyValue(Object(Mittwald\\Typo3Forum\\Domain\\Model\\Forum\\Access), 'affectedGroup', Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult))\n#8 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(291): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->mapObjectToClassProperty(Object(Mittwald\\Typo3Forum\\Domain\\Model\\Forum\\Access), 'affectedGroup', '0')\n#9 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(186): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->thawProperties(Object(Mittwald\\Typo3Forum\\Domain\\Model\\Forum\\Access), Array)\n#10 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(144): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->mapSingleRow('Mittwald\\\\Typo3F...', Array)\n#11 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\QueryResult.php(86): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->map('Mittwald\\\\Typo3F...', Array)\n#12 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\QueryResult.php(242): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult->initialize()\n#13 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(552): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult->rewind()\n#14 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(279): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->mapResultToPropertyValue(Object(Mittwald\\Typo3Forum\\Domain\\Model\\Forum\\Forum), 'acls', Object(TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult))\n#15 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(186): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->thawProperties(Object(Mittwald\\Typo3Forum\\Domain\\Model\\Forum\\Forum), Array)\n#16 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\Mapper\\DataMapper.php(144): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->mapSingleRow('Mittwald\\\\Typo3F...', Array)\n#17 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Generic\\QueryResult.php(115): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\Mapper\\DataMapper->map('Mittwald\\\\Typo3F...', Array)\n#18 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Persistence\\Repository.php(248): TYPO3\\CMS\\Extbase\\Persistence\\Generic\\QueryResult->getFirst()\n#19 C:\\xampp72\\htdocs\\typo3_7\\typo3conf\\ext\\typo3_forum\\Classes\\Controller\\ForumController.php(76): TYPO3\\CMS\\Extbase\\Persistence\\Repository->__call('findOneByForum', Array)\n#20 [internal function]: Mittwald\\Typo3Forum\\Controller\\ForumController->indexAction()\n#21 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Mvc\\Controller\\ActionController.php(283): call_user_func_array(Array, Array)\n#22 C:\\xampp72\\htdocs\\typo3_7\\typo3conf\\ext\\typo3_forum\\Classes\\Controller\\AbstractController.php(123): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()\n#23 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Mvc\\Controller\\ActionController.php(176): Mittwald\\Typo3Forum\\Controller\\AbstractController->callActionMethod()\n#24 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Mvc\\Dispatcher.php(86): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#25 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Mvc\\Web\\FrontendRequestHandler.php(69): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Request), Object(TYPO3\\CMS\\Extbase\\Mvc\\Web\\Response))\n#26 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Core\\Bootstrap.php(206): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()\n#27 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\extbase\\Classes\\Core\\Bootstrap.php(193): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleRequest()\n#28 [internal function]: TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run('', Array)\n#29 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(7315): call_user_func_array(Array, Array)\n#30 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\ContentObject\\UserContentObject.php(40): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction('TYPO3\\\\CMS\\\\Extba...', Array, '')\n#31 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(943): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render(Array)\n#32 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\ContentObject\\ContentObjectRenderer.php(859): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render(Object(TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject), Array)\n#33 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\Controller\\TypoScriptFrontendController.php(3577): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle('USER', Array)\n#34 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\Controller\\TypoScriptFrontendController.php(3522): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript_process(Array)\n#35 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\Controller\\TypoScriptFrontendController.php(3488): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()\n#36 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\Http\\RequestHandler.php(232): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()\n#37 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\core\\Classes\\Core\\Bootstrap.php(307): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#38 C:\\xampp72\\htdocs\\typo3_7\\typo3\\sysext\\frontend\\Classes\\Http\\Application.php(78): TYPO3\\CMS\\Core\\Core\\Bootstrap->handleRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#39 C:\\xampp72\\htdocs\\typo3_7\\index.php(33): TYPO3\\CMS\\Frontend\\Http\\Application->run()\n#40 C:\\xampp72\\htdocs\\typo3_7\\index.php(34): {closure}()\n#41 {main}"}`

thanks & kind regards

Daniel

**Comment by pstranghoener** [comment]
Did you follow the installtion documentation? http://typo3-forum.readthedocs.io/en/master/Configuration/Installation/Index.html 

Looks like your FE Users havent the typo3_forum rights.

**Comment by danielmacht** [comment]
Yes, as i mentioned above, i followed the installation documentation all the way through. The error also exists after reinstalling the extension using the extension manager.

It seemes that the table wasn't created during the extension installation. Based on this assumption I checked the _ext_tables.sql_ file which is located in _typo3conf/ext/typo3_forum/_ and there is no _CREATE TABLE_ statement which creates the named table. 

Next i tried to update the extension (in the extension manager) to migrate the existing fe_users whith no effect.

**Comment by pstranghoener** [comment]
Are you making a migration from mm_forum to typo3_forum? Otherwise there are no migration steps for the users. You can set that in the user settings and user group settings. As it mentioned in the Documentation.

**Comment by danielmacht** [comment]
ok. maybe i missunderstood the update script function. There is no migration from mm_forum. Its a clean, fresh new installation of typo3.

**Comment by pstranghoener** [comment]
Than you have to set it manually. Issue can be closed?

**Comment by danielmacht** [comment]
if u can provide me the nessesary information like field names, datatypes and lenght i can create the missing table _tx_typo3forum_domain_model_user_frontendusergroup_ manually.

**Comment by pstranghoener** [comment]
Why should i do that? I dont know your installation. You can do it in the Backend by all existing FE User. Is is not a support desk for personal installation problems.

**Comment by danielmacht** [comment]
because its your extension!

**Comment by velletti** [comment]
Step ONE 
Include the Static template 
there is a mapping for 
tx_typo3forum_domain_model_user_frontendusergroup to the TYPO3 Default table fe_groups 

So you do not need taht tx_typo3forum_domain_model_user_frontendusergroup table !

Read the Documentation about the 2 needed user Groups: Forum user and Forum Admin ( it is the page [Register and login ](http://typo3-forum.readthedocs.io/en/master/Configuration/RegisterandLogin/Index.html))
