### ISSUE TITLE
[FEATURE] Compatibility with TYPO3 8.7 LTS

### ISSUE THREAD

**Issue by beath** [mittwald/typo3_forum#256]
Is there a plan to make the extension work for 8.7?

**Comment by pstranghoener** [comment]
We have a Version for TYPO3 8.7 but we are not allowed to publish it. Sorry but we can't say anything more to it.

**Comment by sigma67** [comment]
If there will be no TYPO3 8 version, are there plans to publish an open-source version for TYPO3 9 once the LTS version is published?
