### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ibpdd** [mittwald/typo3_forum#258]
Hallo,
ich bin gerade dabei von mm_forum auf das typo3_forum umzusteigen.
Dazu habe ich das mitgelieferte Migrationsscript ausgeführt um die 44525 Posts (10335 Topics) zu übertragen. Dieses hat auch erstmal alles funktioniert.
Wenn ich aber jetzt ein neues Thema eröffnen möchte und auf "Thema erstellen" klicke, lädt er ca. 27sek. um das Thema anzulegen :(
Wenn ich wiederum alle Datensätze lösche und ein leeres neues Forum anlege, lädt er deutlich schneller.

Nach meiner Fehlersuche konnte ich es auf die Funktion addTopic() auf die Zele
[code]$this->topics->attach($topic);[/code]
eingrenzen.
Leider kenn bin ich mich in Extbase nicht so aus um den Fehler selbst zu beheben :(

Kann mir jemand dabei helfen?

Da das mm_forum seit kurzen mit Typo3 6.2x auch langsam läuft (Topicliste), habe ich ein Update auf Typo3 7.6.29 durchgeführt.

Die Webseite läuft bei allinkl.

Freue mich auf eure Antworten.

P.S. Am Server liegt es nicht, da es Lokal auch zu lange ein Post zu erstellen wenn die Datenbank zu groß ist.

Beitrag in typo3.net Forum: https://www.typo3.net/forum/thematik/zeige/thema/126914/

**Comment by velletti** [comment]
nachdem im 👍 
https://github.com/mittwald/typo3_forum/blob/develop/Classes/Domain/Factory/Forum/TopicFactory.php

in 
public function createTopic 
zeile 121: 
		$this->topicRepository->add($topic);
enthalten ist, braucht man den Attach()  im Modell gar nicht.

wir haben ein mm_forum mit ca 200.000 posts in 8 Sprachen un das create Topic geht in 2 sec.

siehe den Kommentar der bei uns im Quelltext steht .. (wir haben einen eigenen Spin Off vom forum von vor 4 Jahren)

	// pbenke 03.02.2016: Not needed, juchee :-), performance goes extreme up, detailed tested
	// $this->topics->attach($topic);

Beim anhängen eines Posts war das ähnlich. 

Falls du auch Performance Probleme bei der Prüfung der Zugriffsrechte hast ( wir haben ziemlich viele user Gruppen (kunde, interessent, Intern, Moderator , Student, Kunde mit Vertrag, betaTester usw usw) 

Abhilfe: 

in der ext_tables.sql


#
# Table structure for table "tx_typo3forum_domain_model_forum_access"
#
CREATE TABLE tx_typo3forum_domain_model_forum_access (
 ....... 
  KEY parent (pid),
  # KEY forum (forum)  
   KEY forum (forum,operation(15))
);

**Comment by ibpdd** [comment]
Danke es hat funktioniert .)
Vielen dank
