### ISSUE TITLE
Upgrade markItUp! to 1.1.14

### ISSUE THREAD

**Issue by neufeind** [mittwald/typo3_forum#26]
Currently ships with version 1.1.12 from 2011. With 1.1.14 from 2013 there is a compat-update for Jquery 1.9+ included. This will allow the forum to be used on sites that already use a newer jQuery.

http://markitup.jaysalvat.com/

(Currently mm_forum ships with a jQuery 1.7.x. But you might be using a separate jQuery-version on a site anyway. The included jQuery might also be considered to be upgraded.)

**Comment by pstranghoener** [comment]
Done in first TER Release
