### ISSUE TITLE
User edit: no link to the edit form

### ISSUE THREAD

**Issue by ineswillenbrock** [mittwald/typo3_forum#264]
My setup: 

PHP 5.6.40
TYPO3 7.6.31
typo3_forum 1.1.1 with 1 changed line (https://github.com/mittwald/typo3_forum/blob/develop/Classes/Domain/Model/Forum/Topic.php#L293) (changed (int) to 1*)

I've got the forum up and running, I get user lists and can post/reply.

- I've set the user edit page via `plugin.tx_typo3forum.settings.pids.UserEdit` to the appropriate PID, 
- Installed the plugin there and set it to User Profile
- Set the Record Storage Page in the plugin to both forum data and fe_user data (as well as via `plugin.tx_typo3forum.persistence.storagePid ` to the same values)
- I don't get links to the edit functionality, I just get to see the same as if I visit a profile of any other user

What did I miss?

Best wishes, Ines

**Comment by pstranghoener** [comment]
Hey, 

for register und and profile edit you have to use the Extension
https://docs.typo3.org/typo3cms/extensions/sf_register/

Best Regards Philipp

**Comment by ineswillenbrock** [comment]
Hey,
I installed that one too, but I don't get the links to edit the profile. And that one seems to have some trouble with information like gender.
Am I right, that typo3.net is essentially typo3_forum with some additions? There the links are shown and it seems that it is the profile edit of typo3_forum.

Best wishes, Ines

**Comment by pstranghoener** [comment]
You have to place the sf_register on a page anywhere and configure it. 

And than you have to the set uid of the page to this setup  plugin.tx_typo3forum.settings.pids.UserEdit 

After that the link will shown in the dashboard of the forum.

**Comment by pstranghoener** [comment]
By the way the templates from typo3.net are very hard customized.

**Comment by ineswillenbrock** [comment]
I suspected that one and I do like that template - but that link is a link :) and should be there
I set `plugin.tx_typo3forum.settings.pids.UserEdit = 61`, put sf_register in edit mode on that page (as well as typo3_forum with user profile) but don't get a link in my dashboard - as long as I don't edit my template :)
Where do I put those changes for the extension?

**Comment by pstranghoener** [comment]
Just link the page where the Plugin is on and when the loggedin user visits the page the profil can be edit. 

I my test installation both links are there, if have done it like the way i said. 

If you want to change the templates of the extension do it in you own theme.

**Comment by ineswillenbrock** [comment]
Me and my English - I thought about contributing that change to the default template. 
In my own instance I copied the template and started changing things around to match my needs but forgot to check if the link to the edit page is even included.
I think, this bug can be closed?

**Comment by pstranghoener** [comment]
Okay, i will close the issue. We are working on the default templates at the moment, to have a better base for that.

**Comment by ineswillenbrock** [comment]
Thanks! I love the look&feel of the Bootstrap one
