### ISSUE TITLE
mm-forum.js does not fit current templates

### ISSUE THREAD

**Issue by neufeind** [mittwald/typo3_forum#64]
Variable currentPageUid is not set in the templates that ship with the extension.
(Please also note that in the Backend-templates shipped it's called currentPageId ... maybe we should rename that there, since there are fewer occurences for the backend and it's less likely others might have adapted those BE-templates to their needs.)

Also mm-forum.js contains quite some code related to boxes that don't ship in the default-templates, it seems.

**Comment by hogiro** [comment]
Hallo,
thanks for such a great extension.

I wanted to try typo3_forum in Typo3 7.6.2 Unfortunately I cannot click any forum and getting on Forum Page the following error:

ReferenceError: currentPageUid is not defined
url: „index.php?id=“+currentPageUid+“&eID=typo3_forum&language=de&tx_typo3forum_…

How could I solve this problem?

Thanks.

Best Regards

**Comment by DavidSporer** [comment]
Hey guys, I've got the same problem that @hogiro mentioned.
I solved it by passing the uid to the page via typoscript and then added a custom JavaScript.
