### ISSUE TITLE
Backend Module

### ISSUE THREAD

**Issue by smichaelsen** [mittwald/typo3_forum#81]
Currently there is a backend module that barely does anything useful. We have to decide wether we need and want a backend module and either implement it properly or remove the corresponding code.

**Comment by sventendo** [comment]
In the same vein, critical code should still make sure we're in the FE context.

I added my own BE module to go through some custom migration tasks and this here triggered an error:
\Mittwald\Typo3Forum\Domain\Model\Forum\Topic::injectTyposcriptService

I wrapped it like this to make it work:
```
		if (TYPO3_MODE == 'FE') {
			$fc = new \TYPO3\CMS\Extbase\Configuration\FrontendConfigurationManager;
			$ts = $this->typoScriptService->convertTypoScriptArrayToPlainArray($fc->getTypoScriptSetup());

			$this->settings = $ts['plugin']['tx_typo3forum']['settings'];
		}

```
