### ISSUE TITLE
Fatal error while opening topics with attachments

### ISSUE THREAD

**Issue by mirkokaufmann** [mittwald/typo3_forum#84]
Fatal error: Call to a member function convertTypoScriptArrayToPlainArray() on a non-object in [...]/typo3conf/ext/typo3_forum/Classes/Domain/Model/Forum/Attachment.php on line 79

**Comment by vendytjung** [comment]
change initializeObject to injectTyposcriptService would help me a lot.
in typo3conf/ext/typo3_forum/Classes/Domain/Model/Forum/Attachment.php

`public function initializeObject() {
		$ts = $this->typoScriptService->convertTypoScriptArrayToPlainArray(\TYPO3\CMS\Extbase\Configuration\FrontendConfigurationManager::getTypoScriptSetup());
		$this->settings = $ts['plugin']['tx_typo3forum']['settings'];
	}`

to 

`public function injectTyposcriptService(\TYPO3\CMS\Extbase\Service\TypoScriptService $typoScriptService) {
		$this->typoScriptService = $typoScriptService;
		$ts = $this->typoScriptService->convertTypoScriptArrayToPlainArray(\TYPO3\CMS\Extbase\Configuration\FrontendConfigurationManager::getTypoScriptSetup());
		$this->settings = $ts['plugin']['tx_typo3forum']['settings'];
	}`

**Comment by kpurrmann** [comment]
#216
