### ISSUE TITLE
Sysfolder for feusers 

### ISSUE THREAD

**Issue by jolantadworczyk** [mittwald/typo3_forum#92]
It has to be an option to set a pid for a fe_users storagefolder.

The extension works without that information, but if you want to send a private message to a another user, you get the error message: no username found.

**Comment by mavoIn** [comment]
I can agree. At the moment you have to add the sys folder in the general storage in the page settings.

**Comment by pstranghoener** [comment]
Its possible with the storagpid you can assign more than one pid seperated with a comma.
